USE [FLEXTIME]
GO



/*Abteilungen erstellen*/
BEGIN
	INSERT INTO ABTEILUNG (NAME) VALUES ('IT');
	INSERT INTO ABTEILUNG (NAME) VALUES ('Management');
	INSERT INTO ABTEILUNG (NAME) VALUES ('Produktion');
END

/*Rechte erstellen*/
BEGIN
	INSERT INTO RECHTE (RECHTSSTUFE) VALUES ('Administrator');
	INSERT INTO RECHTE (RECHTSSTUFE) VALUES ('User');
END

/*Intervall Arten festlegen*/
BEGIN
	INSERT INTO INTERVALL_ART (BESCHREIBUNG ,VERRECHNUNGSFAKTOR) VALUES ('Arbeitszeit', 1);
	INSERT INTO INTERVALL_ART (BESCHREIBUNG, VERRECHNUNGSFAKTOR) VALUES ('Feiertag',1);
	INSERT INTO INTERVALL_ART (BESCHREIBUNG, VERRECHNUNGSFAKTOR) VALUES ('Betriebsferien',0);
	INSERT INTO INTERVALL_ART (BESCHREIBUNG, VERRECHNUNGSFAKTOR) VALUES ('Abwesenheit',0);
END


/*Arbeiter hinzufügen*/
DECLARE @counter INT;
SET @counter = 0;

DECLARE @abteilungId BIGINT;
SET @abteilungId = (SELECT MIN(ABTEILUNG_ID) FROM ABTEILUNG)

DECLARE @rechteId BIGINT;
SET @rechteId = (SELECT MIN(RECHTE_ID) FROM RECHTE)

WHILE @counter < 10
BEGIN
	INSERT INTO ARBEITER ( VORNAME, NACHNAME, RECHTE_ID, ABTEILUNG_ID, STATUS , USERNAME , PASSWORT) VALUES ( 'Vorname'+CAST(@counter AS VARCHAR(16)) , 'Nachname'+CAST(@counter AS VARCHAR(16)), @abteilungId , @rechteId+(@counter%3) , 'ABWESEND' , 'Worker'+CAST(@counter AS VARCHAR(16)), 'secret');
	SET @counter = @counter + 1;
END

/*DECLARE VARIBALES following entries just for one worker*/
DECLARE @intervallId BIGINT;
DECLARE @arbeiterId BIGINT;

/*Arbeitsplanung hinzufügen*/

DECLARE @artId bigint;
SET @artId = (SELECT MIN(ART_ID) FROM INTERVALL_ART)
SET @arbeiterId = (SELECT MIN(ARBEITER_ID) FROM ARBEITER);
BEGIN
	INSERT INTO ZEITINTERVALL (ARBEITER_ID, STARTZEIT, ENDZEIT, ART_ID) VALUES (@arbeiterId, GETDATE(), '2015-01-01 01:00:00', @artId)
	SET @intervallId = (SELECT MAX( INTERVALL_ID) FROM ZEITINTERVALL)
	INSERT INTO ARBEITSPLANUNG (WOCHENTAG, ANZAHL_STUNDEN, INTERVALL_ID) VALUES (0, 8, @intervallId);
END

/*Notiz hinzufügen*/

BEGIN
	INSERT INTO NOTIZEN (ARBEITER_ID, TEXT, DATUM) VALUES (@arbeiterId, 'this is a note', GETDATE())
END

/*Intervalle hinzufügen*/

BEGIN
	INSERT INTO ZEITINTERVALL (ARBEITER_ID, STARTZEIT, ENDZEIT, ART_ID) VALUES (@arbeiterId, GETDATE(), '2015-01-01 01:00:00', @artId)
	INSERT INTO ZEITINTERVALL (ARBEITER_ID, STARTZEIT, ENDZEIT, ART_ID) VALUES (@arbeiterId, GETDATE(), '2015-02-01 02:00:00', @artId+1)
	INSERT INTO ZEITINTERVALL (ARBEITER_ID, STARTZEIT, ENDZEIT, ART_ID) VALUES (@arbeiterId, GETDATE(), '2015-03-01 02:00:00', @artId+2)
	INSERT INTO ZEITINTERVALL (ARBEITER_ID, STARTZEIT, ENDZEIT, ART_ID) VALUES (@arbeiterId, GETDATE(), '2015-04-01 03:00:00', @artId+3)
END

/*Rückvergütete überstunden hinzufügen*/

BEGIN
	INSERT INTO RUECKVERGUETETE_UEBERSTUNDEN (ARBEITER_ID, DATUM, ANZAHL) VALUES (@arbeiterId, '2015-04-01 03:00:00', 8)
END

/*Arbeitspensum hinzufügen*/

BEGIN
	INSERT INTO ZEITINTERVALL (ARBEITER_ID, STARTZEIT, ENDZEIT, ART_ID) VALUES (@arbeiterId, GETDATE(), '2015-01-01 01:00:00', @artId)
	SET @intervallId = (SELECT MAX( INTERVALL_ID) FROM ZEITINTERVALL)
	INSERT INTO ARBEITSPENSUM(BESCHAEFTIGUNGSGRAD, INTERVALL_ID) VALUES (100, @intervallId);
END
